initialization
inicializarDesdeInterior: unDesdeInterior haciaInterior: unHaciaInterior mercaderiaFragil: unaMercaderiaFragil adicionalFragil: unAdicionalFragil distanciaAcordada: unaDistanciaAcordada adicionalDistancia: unAdicionalDistancia

	desdeInterior := unDesdeInterior.
	haciaInterior := unHaciaInterior.
	mercaderiaFragil := unaMercaderiaFragil.
	adicionalFragil := unAdicionalFragil.
	distanciaAcordada := unaDistanciaAcordada.
	adicionalDistancia := unAdicionalDistancia