initialization
inicializarConDescripcion: unaDescripcion conNombre: unNombre conValorBase: unValorBase conEsDeALtura: siEsDeAltura conValorAdicionalAltura: unValorAdicionalAltura conValorAdicionalEmbalaje: unValorAdicionalEmbalaje conCapacidad: unaCapacidad haciaInterior: siHaciaInterior desdeInterior: siDesdeInterior conMercaderiaFragil: siMercaderiaFragil conValorAdicionalFragil: unValorAdicionalFragil conDistanciaAcordada: unaDistanciaAcordada conValorAdicionalPorDistancia: unValorAdicionalPorDistancia

	self
		inicializarConDescripcion: unaDescripcion
		conNombre: unNombre
		conValorBase: unValorBase
		conEsDeALtura: siEsDeAltura
		conValorAdicionalAltura: unValorAdicionalAltura
		conValorAdicionalEmbalaje: unValorAdicionalEmbalaje
		conCapacidad: unaCapacidad.
	haciaInterior := siHaciaInterior.
	desdeInterior := siDesdeInterior.
	esMercaderiaFragil := siMercaderiaFragil.
	valorAdicionalFragil := unValorAdicionalFragil.
	distanciaAcordada := unaDistanciaAcordada.
	valorAdicionalPorDistancia := unValorAdicionalPorDistancia