as yet unclassified
crearConDescripcion: unaDescripcion conNombre: unNombre conValorBase: unValorBase conEsDeALtura: siEsDeAltura conValorAdicionalAltura: unValorAdicionalAltura conValorAdicionalEmbalaje: unValorAdicionalEmbalaje conCapacidad: unaCapacidad
	| temp |
	temp := self new.
	temp inicializarConDescripcion: unaDescripcion conNombre: unNombre conValorBase: unValorBase conEsDeALtura: siEsDeAltura conValorAdicionalAltura: unValorAdicionalAltura conValorAdicionalEmbalaje: unValorAdicionalEmbalaje conCapacidad: unaCapacidad.
	^ temp.