as yet unclassified
inicializarConDatosPersonales: losDatos conLegajo: unLegajo conFechaIngreso: unaFecha conSueldoBasico: unSueldo conHorarioTrabajo: unHorario conHorasExtra: unasHorasExtra conTituloUniversitario: unTituloUniversitario
	self inicializarConDatosPersonales: losDatos conLegajo: unLegajo conFechaIngreso: unaFecha conSueldoBasico: unSueldo conHorarioTrabajo: unHorario.
	horasExtra := unasHorasExtra.
	tituloUniversitario := unTituloUniversitario.