as yet unclassified
inicializarConDescripcion: unaDescripcion conNombre: unNombre conValorBase: unValorBase conTamañoDisponible: unTamañoDisponible conAislamientoTermico: tieneAislamientoTermico conGuardaDeLlave: tieneGuardaDeLlave
	self inicializarConDescripcion: unaDescripcion conNombre: unNombre conValorBase: unValorBase.
	tamañoDisponible := unTamañoDisponible.
	aislamientoTermico := tieneAislamientoTermico.
	guardaDeLlave := tieneGuardaDeLlave.