initialization
inicializarConEmpleados: unaColEmpleados conPorcentajeVendedor: unPorcentajeVendedor conTablaCargos: unaTablaCargos conValorTituloUniversitario: unValorTituloUniversitario conValorHoraExtra: unValorHoraExtra
	empleados := unaColEmpleados.
	porcentajeVendedor := unPorcentajeVendedor.
	tablaCargos := unaTablaCargos.
	valorTituloUniversitario := unValorTituloUniversitario.
	valorHoraExtra := unValorHoraExtra.