as yet unclassified
inicializarConRazonSocial: unaRazonSocial conPaginaWeb: unaPaginaWeb conTelefonoContacto: unTelefonoContacto conDireccion: unaDireccion conServicios: unaColServicios conClientes: unaColClientes conContratos: unaColContratos
	razonSocial := unaRazonSocial.
	paginaWeb := unaPaginaWeb.
	telefonoContacto := unTelefonoContacto.
	direccion := unaDireccion.
	clientes := unaColClientes.
	servicios := unaColServicios.
	contratos := unaColContratos.
	
    