initialization
inicializarRazonSocial: unaRazonSocial paginaWeb: unaPaginaWeb telefonoContacto: unTelefonoContacto direccion: unaDireccion servicios: unaColServicios clientes: unaColClientes contratos: unaColContratos

	razonSocial := unaRazonSocial.
	paginaWeb := unaPaginaWeb.
	telefonoContacto := unTelefonoContacto.
	direccion := unaDireccion.
	clientes := unaColClientes.
	servicios := unaColServicios.
	contratos := unaColContratos