as yet unclassified
inicializarConDescripcion: unaDescripcion conNombre: unNombre conValorBase: unValorBase conEsDeALtura: siEsDeAltura conValorAdicionalAltura: unValorAdicionalAltura conValorAdicionalEmbalaje: unValorAdicionalEmbalaje conCapacidad: unaCapacidad conIncluyeCarga: siIncluyeCarga conIncluyeDescarga: siIncluyeDescarga conDistanciaMaxima: unaDistanciaMaxima
	self inicializarConDescripcion: unaDescripcion conNombre: unNombre conValorBase: unValorBase conEsDeALtura: siEsDeAltura conValorAdicionalAltura: unValorAdicionalAltura conValorAdicionalEmbalaje: unValorAdicionalEmbalaje conCapacidad: unaCapacidad.
	incluyeCarga := siIncluyeCarga.
	incluyeDescarga := siIncluyeDescarga.
	distanciaMaxima := unaDistanciaMaxima.
	